# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XTech' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XTech
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'SVProgressHUD'
pod 'ChameleonFramework'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Facebook'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Charts'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'SwiftMQTT'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
    end
  end
end
